### ISSUE TITLE
Keep original filename

### ISSUE THREAD

**Issue by martinmaillard** [keichan34/exfile#22]
Is there any way to keep the original file name ?

I thought I could write my own `hasher`, but the `hash` function does not have access to the file name...

A cleaner way would be to keep the file name in another field and restore it when the file is downloaded, but I have no idea how to do this...

**Comment by keichan34** [comment]
Not at the moment. I'll think of a way to either make the filename available to you in the hasher or restore it when it's being downloaded and get back to you on this thread.

**Comment by asiniy** [comment]
@keichan34 what do you think about storing a file name in the separate field, like in refile?

**Comment by loongmxbt** [comment]
How can I customize the upload filename? In some cases, I have to remain the filename info in the file in storage. Backup or send email attachments to someone.
1. Customize upload file name - filename.docx -> filename_username_3hY83x.docx
2. Customize download name - If I have a field saving the original filename, but the file goes into xHu7dnx.pdf, I can modify header and download it with the original filename.

**Comment by asiniy** [comment]
@loongmxbt original `refile` approach is a little bit different. You are saving filename to database and it returns the name in in `exfile_url` link

**Comment by keichan34** [comment]
@loongmxbt Hi, sorry for the delay. I've implemented this on master -- to save the filename to the database, follow [this example](https://github.com/keichan34/exfile/blob/7441e1b35728b9c27f486ccf023ba327ca0f5d73/README.md#storing-metadata-to-the-database). To customize the filename as it's being output using `exfile_url` or `exfile_path`, you can use the `filename` option:

``` elixir
exfile_path(file, filename: "my-file.jpg")
```

Let me know if you have any questions or troubles. I'm hoping to release a version to Hex with this in the coming weeks.

**Comment by asiniy** [comment]
@keichan34 awesome

**Comment by loongmxbt** [comment]
@keichan34  Awesome! Thanks for the work! But still one strange question. It seems my `|> cast_filename(:file)` doesn't work, the `filename` remains empty.

``` elixir
defmodule Confer.Paper do
  use Confer.Web, :model

  import Exfile.Ecto.ValidateContentType
  import Exfile.Ecto.CastContentType
  import Exfile.Ecto.CastFilename

  schema "papers" do
    field :title, :string
    field :file, Exfile.Ecto.File
    field :content_type, :string
    field :filename, :string
    belongs_to :topic, Confer.Topic
    belongs_to :user, Confer.User
    has_many :reviews, Confer.Review

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:title, :file, :topic_id, :user_id, :content_type, :filename])
    |> validate_required([:title, :topic_id, :file, :user_id])
    |> validate_content_type(:file, ~w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document))
    |> cast_content_type(:file, :content_type)
    |> cast_filename(:file, :filename)
  end
end
```

When I upload a pdf, content_type has value, but filename remains empty.

```
FILENAME    
CONTENT TYPE    application/pdf
```

Is it because something wrong with `file.meta["filename"]` causes it to be empty? My upload form is like:

``` html
  <div class="form-group">
    <%= label f, "Upload paper", class: "control-label" %>
    <%= file_input f, :file, class: "form-control" %>
    <%= error_tag f, :file %>
  </div>
```

Wish some help!

**Comment by martinmaillard** [comment]
Thank you @keichan34!
I just tried to implement it and storing the filename works properly. However, I get the following error when accessing the URL generated by `exfile_path attachment, filename: "a_file_name.pdf"`:

```
processing using convert failed with reason no_processor
```

Is it an error in my configuration?

**Comment by asiniy** [comment]
@martinmaillard try it with meta processor running. It looks like a bug of exfile. It doesn't have lazy implementation of `meta` processor in `cast_filename`
