### ISSUE TITLE
Make file format validation easier & add proper documentation

### ISSUE THREAD

**Issue by keichan34** [keichan34/exfile#27]
- [x] Use the `file` command to identify MIME type if available
- [x] Add documentation

**Comment by keichan34** [comment]
@asiniy Go ahead! I was thinking about making a new processor and packaging it in exfile (and not exfile-imagemagick). Send a PR and I'll review it. If you aren't sure about it but you want me to look at it anyways, just send the PR and tell me not to merge immediately.

**Comment by asiniy** [comment]
@keichan34 thanks! I think this functionality will take more than half of the week anyway, because I need to understand essentials of the project

**Comment by asiniy** [comment]
@keichan34 close it?
