### ISSUE TITLE
Exfile - how to document?

### ISSUE THREAD

**Issue by asiniy** [keichan34/exfile#29]
I found exfile very powerful library, but lack of documentation makes me stressful. I want to share details - i.e., how to test this library functionality, with `ex_unit` & `ex_machina`.

But I don't know where I can do it. Usual solutions:
- Directly to README.md
- Work with wiki
- Create a `docs` directory, and puts recipes to it

I prefer the first one, but I'm not sure about correctness of my choice. What could you say?

**Comment by keichan34** [comment]
API documentation is automatically generated with exdoc, and published to [hexdocs](https://hexdocs.pm/exfile/readme.html) (although, it isn't perfect). For instructions on how to test exfile, those should probably go in to `README.md`, or some other markdown file in the root directory if it doesn't belong there. If you want to help improve documentation, it would be great if you could send a PR with what you think makes sense and we can discuss from there :)

**Comment by asiniy** [comment]
@keichan34 got it
