### ISSUE TITLE
Doesn't work with prod

### ISSUE THREAD

**Issue by noma4i** [keichan34/exfile#44]
Looks like SuperVisor is running under Mix.\* which is not compiled with exrm or distillery.

```
Slogan: Kernel pid terminated (application_controller) ({application_start_failure,exfile,{{undef,[{'Elixir.Mix',env,[],[]},{'Elixir.Exfile.Supervisor',init,1,[{file,"lib/exfile/supervisor.ex"},{line,17}]}
```

**Comment by keichan34** [comment]
Ahh, I see. It's raising on this: `if Mix.env == :test do`. I'll be able to fix this soon.

**Comment by keichan34** [comment]
@noma4i I pushed a commit that I think will fix this, can you test it out with your setup?

**Comment by noma4i** [comment]
Works
