### ISSUE TITLE
Publishing 0.3.5?

### ISSUE THREAD

**Issue by yury-dymov** [keichan34/exfile#57]
Hey, thank you for the nice library.

I wanted to use it in my project but faced an issue: I want to use new validation APIs introduced in 0.3.5 and `exfile-imagemagick` at the same time. It doesn't work out-of-the-box and I don't want to fork everything and make things work together myself.

So any ideas when stuff will be published and work together smoothly?

**Comment by scarfacedeb** [comment]
Any news on this one?

**Comment by keichan34** [comment]
@yury-dymov @scarfacedeb I've just released v0.3.6.
